% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={IDS572-HW4},
  pdfauthor={Amin Abbasi},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{IDS572-HW4}
\author{Amin Abbasi}
\date{2024-11-23}

\begin{document}
\maketitle

\phantomsection\label{r}%
\begin{verbatim}

install.packages("smotefamily")
install.packages("DMwR2")
install.packages("caret")
install.packages("rpart")   # Install and load rpart for decision trees
install.packages("randomForest") # Install and load randomForest
install.packages("e1071") # Install and load e1071 for Naive Bayes
install.packages("adabag")  # Install and load adabag for AdaBoost
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readxl)  }\CommentTok{\# For reading Excel files}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'readxl' was built under R version 4.3.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(smotefamily)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'smotefamily' was built under R version 4.3.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(DMwR2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'DMwR2' was built under R version 4.3.3
\end{verbatim}

\begin{verbatim}
## Registered S3 method overwritten by 'quantmod':
##   method            from
##   as.zoo.data.frame zoo
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(caret)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'caret' was built under R version 4.3.3
\end{verbatim}

\begin{verbatim}
## Loading required package: ggplot2
\end{verbatim}

\begin{verbatim}
## Warning: package 'ggplot2' was built under R version 4.3.3
\end{verbatim}

\begin{verbatim}
## Loading required package: lattice
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(reshape2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'reshape2' was built under R version 4.3.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(rpart)}
\FunctionTok{library}\NormalTok{(pROC) }\CommentTok{\# for ROC curve}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'pROC' was built under R version 4.3.3
\end{verbatim}

\begin{verbatim}
## Type 'citation("pROC")' for a citation.
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'pROC'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     cov, smooth, var
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(randomForest)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'randomForest' was built under R version 4.3.3
\end{verbatim}

\begin{verbatim}
## randomForest 4.7-1.2
\end{verbatim}

\begin{verbatim}
## Type rfNews() to see new features/changes/bug fixes.
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'randomForest'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:ggplot2':
## 
##     margin
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(e1071)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'e1071' was built under R version 4.3.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(adabag)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'adabag' was built under R version 4.3.3
\end{verbatim}

\begin{verbatim}
## Loading required package: foreach
\end{verbatim}

\begin{verbatim}
## Warning: package 'foreach' was built under R version 4.3.3
\end{verbatim}

\begin{verbatim}
## Loading required package: doParallel
\end{verbatim}

\begin{verbatim}
## Warning: package 'doParallel' was built under R version 4.3.3
\end{verbatim}

\begin{verbatim}
## Loading required package: iterators
\end{verbatim}

\begin{verbatim}
## Warning: package 'iterators' was built under R version 4.3.3
\end{verbatim}

\begin{verbatim}
## Loading required package: parallel
\end{verbatim}

\#\#Importing the Dataset

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load your dataset (replace \textquotesingle{}your\_dataset.csv\textquotesingle{} with your actual dataset file)}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"Retention Modeling at Scholastic Travel Company (A)\_ Student Spreadsheet.xlsx"}\NormalTok{, }\AttributeTok{sheet =} \StringTok{"Data"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Expecting numeric in A2393 / R2393C1: got 'Data source: Company data
## adjusted by author using unspecified constants.'
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Convert the target variable to a factor}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.} \OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\#\#Exploring the dataset

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# View the structure of the dataset}
\FunctionTok{str}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## tibble [2,392 x 56] (S3: tbl_df/tbl/data.frame)
##  $ ID                            : num [1:2392] 1 2 3 4 5 6 7 8 9 10 ...
##  $ Program.Code                  : chr [1:2392] "HS" "HC" "HD" "HN" ...
##  $ From.Grade                    : chr [1:2392] "4" "8" "8" "9" ...
##  $ To.Grade                      : chr [1:2392] "4" "8" "8" "12" ...
##  $ Group.State                   : chr [1:2392] "CA" "AZ" "FL" "VA" ...
##  $ Is.Non.Annual.                : num [1:2392] 0 0 0 1 0 0 1 0 0 0 ...
##  $ Days                          : num [1:2392] 1 7 3 3 6 4 6 8 8 4 ...
##  $ Travel.Type                   : chr [1:2392] "A" "A" "A" "B" ...
##  $ Departure.Date                : POSIXct[1:2392], format: "2011-01-14" "2011-01-14" ...
##  $ Return.Date                   : POSIXct[1:2392], format: "2011-01-14" "2011-01-21" ...
##  $ Deposit.Date                  : POSIXct[1:2392], format: "2010-08-30" "2009-11-15" ...
##  $ Special.Pay                   : chr [1:2392] "NA" "CP" "NA" "NA" ...
##  $ Tuition                       : num [1:2392] 424 2350 1181 376 865 ...
##  $ FRP.Active                    : num [1:2392] 25 9 17 0 40 9 16 10 30 51 ...
##  $ FRP.Cancelled                 : num [1:2392] 3 9 6 0 8 4 4 0 0 1 ...
##  $ FRP.Take.up.percent.          : num [1:2392] 0.424 0.409 0.708 0 0.494 0.9 0.64 0.769 0.577 0.773 ...
##  $ Early.RPL                     : chr [1:2392] "40266" "40106" "40297" "NA" ...
##  $ Latest.RPL                    : chr [1:2392] "40402" "40400" "40406" "NA" ...
##  $ Cancelled.Pax                 : num [1:2392] 3 11 6 1 9 3 5 1 0 1 ...
##  $ Total.Discount.Pax            : num [1:2392] 4 3 3 0 8 1 2 1 4 6 ...
##  $ Initial.System.Date           : chr [1:2392] "40263" "40088" "40206" "40470" ...
##  $ Poverty.Code                  : chr [1:2392] "B" "C" "C" NA ...
##  $ Region                        : chr [1:2392] "Southern California" "Other" "Other" "Other" ...
##  $ CRM.Segment                   : chr [1:2392] "4" "10" "10" "7" ...
##  $ School.Type                   : chr [1:2392] "PUBLIC" "PUBLIC" "PUBLIC" "CHD" ...
##  $ Parent.Meeting.Flag           : num [1:2392] 1 1 1 0 1 1 1 1 1 1 ...
##  $ MDR.Low.Grade                 : chr [1:2392] "K" "7" "6" NA ...
##  $ MDR.High.Grade                : chr [1:2392] "5" "8" "8" "NA" ...
##  $ Total.School.Enrollment       : num [1:2392] 927 850 955 NA 720 939 225 NA 500 635 ...
##  $ Income.Level                  : chr [1:2392] "Q" "A" "O" NA ...
##  $ EZ.Pay.Take.Up.Rate           : num [1:2392] 0.17 0.091 0.042 0 0.383 0.1 0.08 0 0.231 0.136 ...
##  $ School.Sponsor                : num [1:2392] 1 0 0 0 0 0 0 0 0 0 ...
##  $ SPR.Product.Type              : chr [1:2392] "CA History" "East Coast" "East Coast" "East Coast" ...
##  $ SPR.New.Existing              : chr [1:2392] "EXISTING" "EXISTING" "EXISTING" "EXISTING" ...
##  $ FPP                           : num [1:2392] 59 22 24 18 81 10 25 13 52 66 ...
##  $ Total.Pax                     : num [1:2392] 63 25 27 18 89 11 27 14 56 72 ...
##  $ SPR.Group.Revenue             : num [1:2392] 424 2350 1181 376 865 ...
##  $ NumberOfMeetingswithParents   : num [1:2392] 1 2 1 0 1 1 1 1 1 1 ...
##  $ FirstMeeting                  : chr [1:2392] "40402" "40134" "40434" "NA" ...
##  $ LastMeeting                   : chr [1:2392] "40402" "40417" "40434" "NA" ...
##  $ DifferenceTraveltoFirstMeeting: chr [1:2392] "155" "423" "124" "NA" ...
##  $ DifferenceTraveltoLastMeeting : chr [1:2392] "155" "140" "124" "NA" ...
##  $ SchoolGradeTypeLow            : chr [1:2392] "Elementary" "Middle" "Middle" "High" ...
##  $ SchoolGradeTypeHigh           : chr [1:2392] "Elementary" "Middle" "Middle" "High" ...
##  $ SchoolGradeType               : chr [1:2392] "Elementary->Elementary" "Middle->Middle" "Middle->Middle" "High->High" ...
##  $ DepartureMonth                : chr [1:2392] "January" "January" "January" "January" ...
##  $ GroupGradeTypeLow             : chr [1:2392] "K" "Middle" "Middle" "Undefined" ...
##  $ GroupGradeTypeHigh            : chr [1:2392] "Elementary" "Middle" "Middle" "Undefined" ...
##  $ GroupGradeType                : chr [1:2392] "K->Elementary" "Middle->Middle" "Middle->Middle" "Undefined->Undefined" ...
##  $ MajorProgramCode              : chr [1:2392] "H" "H" "H" "H" ...
##  $ SingleGradeTripFlag           : num [1:2392] 1 1 1 0 0 0 0 1 1 1 ...
##  $ FPP.to.School.enrollment      : chr [1:2392] "6.3646170000000002E-2" "2.5882353E-2" "2.5130889999999999E-2" "NA" ...
##  $ FPP.to.PAX                    : num [1:2392] 0.937 0.88 0.889 1 0.91 ...
##  $ Num.of.Non_FPP.PAX            : num [1:2392] 4 3 3 0 8 1 2 1 4 6 ...
##  $ SchoolSizeIndicator           : chr [1:2392] "L" "L" "L" NA ...
##  $ Retained.in.2012.             : Factor w/ 2 levels "0","1": 2 2 2 1 1 2 1 1 2 2 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Get a summary of the dataset}
\FunctionTok{summary}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        ID       Program.Code        From.Grade          To.Grade        
##  Min.   :   1   Length:2392        Length:2392        Length:2392       
##  1st Qu.: 598   Class :character   Class :character   Class :character  
##  Median :1195   Mode  :character   Mode  :character   Mode  :character  
##  Mean   :1195                                                           
##  3rd Qu.:1792                                                           
##  Max.   :2389                                                           
##  NA's   :3                                                              
##  Group.State        Is.Non.Annual.       Days        Travel.Type       
##  Length:2392        Min.   :0.000   Min.   : 1.000   Length:2392       
##  Class :character   1st Qu.:0.000   1st Qu.: 4.000   Class :character  
##  Mode  :character   Median :0.000   Median : 5.000   Mode  :character  
##                     Mean   :0.154   Mean   : 4.575                     
##                     3rd Qu.:0.000   3rd Qu.: 5.000                     
##                     Max.   :1.000   Max.   :12.000                     
##                     NA's   :3       NA's   :3                          
##  Departure.Date                    Return.Date                    
##  Min.   :2011-01-14 00:00:00.00   Min.   :2011-01-14 00:00:00.00  
##  1st Qu.:2011-04-09 00:00:00.00   1st Qu.:2011-04-12 00:00:00.00  
##  Median :2011-05-17 00:00:00.00   Median :2011-05-20 00:00:00.00  
##  Mean   :2011-05-07 18:20:38.68   Mean   :2011-05-11 11:57:53.42  
##  3rd Qu.:2011-06-07 00:00:00.00   3rd Qu.:2011-06-10 00:00:00.00  
##  Max.   :2011-06-30 00:00:00.00   Max.   :2011-07-05 00:00:00.00  
##  NA's   :3                        NA's   :3                       
##   Deposit.Date                    Special.Pay           Tuition    
##  Min.   :2009-09-25 00:00:00.00   Length:2392        Min.   :  79  
##  1st Qu.:2010-10-15 00:00:00.00   Class :character   1st Qu.:1174  
##  Median :2010-10-28 00:00:00.00   Mode  :character   Median :1700  
##  Mean   :2010-10-24 19:42:37.22                      Mean   :1615  
##  3rd Qu.:2010-11-05 00:00:00.00                      3rd Qu.:2048  
##  Max.   :2011-10-30 00:00:00.00                      Max.   :4200  
##  NA's   :3                                           NA's   :3     
##    FRP.Active     FRP.Cancelled    FRP.Take.up.percent.  Early.RPL        
##  Min.   :  0.00   Min.   : 0.000   Min.   :0.0000       Length:2392       
##  1st Qu.:  6.00   1st Qu.: 1.000   1st Qu.:0.4550       Class :character  
##  Median : 12.00   Median : 2.000   Median :0.6000       Mode  :character  
##  Mean   : 16.87   Mean   : 3.306   Mean   :0.5707                         
##  3rd Qu.: 23.00   3rd Qu.: 4.000   3rd Qu.:0.7270                         
##  Max.   :257.00   Max.   :45.000   Max.   :1.0000                         
##  NA's   :3        NA's   :3        NA's   :3                              
##   Latest.RPL        Cancelled.Pax    Total.Discount.Pax Initial.System.Date
##  Length:2392        Min.   : 0.000   Min.   : 0.000     Length:2392        
##  Class :character   1st Qu.: 2.000   1st Qu.: 1.000     Class :character   
##  Mode  :character   Median : 4.000   Median : 2.000     Mode  :character   
##                     Mean   : 4.807   Mean   : 2.954                        
##                     3rd Qu.: 6.000   3rd Qu.: 4.000                        
##                     Max.   :39.000   Max.   :47.000                        
##                     NA's   :3        NA's   :3                             
##  Poverty.Code          Region          CRM.Segment        School.Type       
##  Length:2392        Length:2392        Length:2392        Length:2392       
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##                                                                             
##  Parent.Meeting.Flag MDR.Low.Grade      MDR.High.Grade    
##  Min.   :0.0000      Length:2392        Length:2392       
##  1st Qu.:1.0000      Class :character   Class :character  
##  Median :1.0000      Mode  :character   Mode  :character  
##  Mean   :0.8589                                           
##  3rd Qu.:1.0000                                           
##  Max.   :1.0000                                           
##  NA's   :3                                                
##  Total.School.Enrollment Income.Level       EZ.Pay.Take.Up.Rate
##  Min.   :  19.0          Length:2392        Min.   :0.0000     
##  1st Qu.: 360.0          Class :character   1st Qu.:0.1000     
##  Median : 597.0          Mode  :character   Median :0.2000     
##  Mean   : 648.4                             Mean   :0.2079     
##  3rd Qu.: 825.8                             3rd Qu.:0.2920     
##  Max.   :3990.0                             Max.   :1.7500     
##  NA's   :94                                 NA's   :3          
##  School.Sponsor   SPR.Product.Type   SPR.New.Existing        FPP       
##  Min.   :0.0000   Length:2392        Length:2392        Min.   :  2.0  
##  1st Qu.:0.0000   Class :character   Class :character   1st Qu.: 12.0  
##  Median :0.0000   Mode  :character   Mode  :character   Median : 23.0  
##  Mean   :0.1059                                         Mean   : 31.3  
##  3rd Qu.:0.0000                                         3rd Qu.: 41.0  
##  Max.   :1.0000                                         Max.   :286.0  
##  NA's   :3                                              NA's   :3      
##    Total.Pax      SPR.Group.Revenue NumberOfMeetingswithParents
##  Min.   :  2.00   Min.   :  79      Min.   :0.000              
##  1st Qu.: 14.00   1st Qu.:1174      1st Qu.:1.000              
##  Median : 26.00   Median :1700      Median :1.000              
##  Mean   : 34.25   Mean   :1615      Mean   :1.102              
##  3rd Qu.: 44.00   3rd Qu.:2048      3rd Qu.:1.000              
##  Max.   :313.00   Max.   :4200      Max.   :2.000              
##  NA's   :3        NA's   :3         NA's   :3                  
##  FirstMeeting       LastMeeting        DifferenceTraveltoFirstMeeting
##  Length:2392        Length:2392        Length:2392                   
##  Class :character   Class :character   Class :character              
##  Mode  :character   Mode  :character   Mode  :character              
##                                                                      
##                                                                      
##                                                                      
##                                                                      
##  DifferenceTraveltoLastMeeting SchoolGradeTypeLow SchoolGradeTypeHigh
##  Length:2392                   Length:2392        Length:2392        
##  Class :character              Class :character   Class :character   
##  Mode  :character              Mode  :character   Mode  :character   
##                                                                      
##                                                                      
##                                                                      
##                                                                      
##  SchoolGradeType    DepartureMonth     GroupGradeTypeLow  GroupGradeTypeHigh
##  Length:2392        Length:2392        Length:2392        Length:2392       
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##                                                                             
##  GroupGradeType     MajorProgramCode   SingleGradeTripFlag
##  Length:2392        Length:2392        Min.   :0.0000     
##  Class :character   Class :character   1st Qu.:0.0000     
##  Mode  :character   Mode  :character   Median :1.0000     
##                                        Mean   :0.5567     
##                                        3rd Qu.:1.0000     
##                                        Max.   :1.0000     
##                                        NA's   :3          
##  FPP.to.School.enrollment   FPP.to.PAX     Num.of.Non_FPP.PAX
##  Length:2392              Min.   :0.6000   Min.   : 0.000    
##  Class :character         1st Qu.:0.8824   1st Qu.: 1.000    
##  Mode  :character         Median :0.9091   Median : 2.000    
##                           Mean   :0.9007   Mean   : 2.954    
##                           3rd Qu.:0.9333   3rd Qu.: 4.000    
##                           Max.   :1.0000   Max.   :47.000    
##                           NA's   :3        NA's   :3         
##  SchoolSizeIndicator Retained.in.2012.
##  Length:2392         0   : 938        
##  Class :character    1   :1451        
##  Mode  :character    NA's:   3        
##                                       
##                                       
##                                       
## 
\end{verbatim}

\#\#Preprocessing Data

\#Remove Columns with Date Values \#Replace NA and ``NA'' (as text) with
``\,'' in all columns except ``Special.Pay''

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Remove specific columns by name}
\NormalTok{data }\OtherTok{\textless{}{-}}\NormalTok{ data[, }\SpecialCharTok{!}\FunctionTok{names}\NormalTok{(data) }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"Return.Date"}\NormalTok{, }\StringTok{"Deposit.Date"}\NormalTok{, }\StringTok{"Departure.Date"}\NormalTok{, }\StringTok{"Early.RPL"}\NormalTok{, }\StringTok{"Latest.RPL"}\NormalTok{, }\StringTok{"FirstMeeting"}\NormalTok{, }\StringTok{"LastMeeting"}\NormalTok{, }\StringTok{"Initial.System.Date"}\NormalTok{,}\StringTok{"ID"}\NormalTok{ )]}

\CommentTok{\# Check the structure of the updated dataset}
\CommentTok{\#str(data)  \# Confirm that the columns have been removed}


\CommentTok{\# Replace "NA" and "" with NA in all columns}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\FunctionTok{lapply}\NormalTok{(data, }\ControlFlowTok{function}\NormalTok{(column) \{}
  \CommentTok{\# Replace empty strings or "NA" (string) with actual NA}
\NormalTok{  column[column }\SpecialCharTok{==} \StringTok{""} \SpecialCharTok{|}\NormalTok{ column }\SpecialCharTok{==} \StringTok{"NA"}\NormalTok{] }\OtherTok{\textless{}{-}} \ConstantTok{NA}
  \FunctionTok{return}\NormalTok{(column)}
\NormalTok{\}), }\AttributeTok{stringsAsFactors =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\#Handling Missing Values Check Missing Values in Each Column

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Count missing values in each column}
\FunctionTok{colSums}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(data))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                   Program.Code                     From.Grade 
##                              3                            130 
##                       To.Grade                    Group.State 
##                            153                              3 
##                 Is.Non.Annual.                           Days 
##                              3                              3 
##                    Travel.Type                    Special.Pay 
##                              3                           1922 
##                        Tuition                     FRP.Active 
##                              3                              3 
##                  FRP.Cancelled           FRP.Take.up.percent. 
##                              3                              3 
##                  Cancelled.Pax             Total.Discount.Pax 
##                              3                              3 
##                   Poverty.Code                         Region 
##                            602                              3 
##                    CRM.Segment                    School.Type 
##                              7                              3 
##            Parent.Meeting.Flag                  MDR.Low.Grade 
##                              3                             71 
##                 MDR.High.Grade        Total.School.Enrollment 
##                             71                             94 
##                   Income.Level            EZ.Pay.Take.Up.Rate 
##                             65                              3 
##                 School.Sponsor               SPR.Product.Type 
##                              3                              3 
##               SPR.New.Existing                            FPP 
##                              3                              3 
##                      Total.Pax              SPR.Group.Revenue 
##                              3                              3 
##    NumberOfMeetingswithParents DifferenceTraveltoFirstMeeting 
##                              3                            340 
##  DifferenceTraveltoLastMeeting             SchoolGradeTypeLow 
##                            340                              3 
##            SchoolGradeTypeHigh                SchoolGradeType 
##                              3                              3 
##                 DepartureMonth              GroupGradeTypeLow 
##                              3                              3 
##             GroupGradeTypeHigh                 GroupGradeType 
##                              3                              3 
##               MajorProgramCode            SingleGradeTripFlag 
##                              3                              3 
##       FPP.to.School.enrollment                     FPP.to.PAX 
##                             94                              3 
##             Num.of.Non_FPP.PAX            SchoolSizeIndicator 
##                              3                             94 
##              Retained.in.2012. 
##                              3
\end{verbatim}

\#handle missing values in the dataset by replacing:

Missing values in numerical columns with the mean. Missing values in
categorical columns with the mode.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load the dataset}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"Step1\_removeNAs.csv"}\NormalTok{, }\AttributeTok{stringsAsFactors =} \ConstantTok{FALSE}\NormalTok{)}

\CommentTok{\# Function to calculate the mode}
\NormalTok{calculate\_mode }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(column) \{}
\NormalTok{  unique\_values }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(column)}
\NormalTok{  unique\_values }\OtherTok{\textless{}{-}}\NormalTok{ unique\_values[}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(unique\_values)]  }\CommentTok{\# Exclude NA from calculation}
\NormalTok{  mode\_value }\OtherTok{\textless{}{-}}\NormalTok{ unique\_values[}\FunctionTok{which.max}\NormalTok{(}\FunctionTok{tabulate}\NormalTok{(}\FunctionTok{match}\NormalTok{(column, unique\_values)))]}
  \FunctionTok{return}\NormalTok{(mode\_value)}
\NormalTok{\}}

\CommentTok{\# Separate numeric and categorical columns}
\NormalTok{numeric\_columns }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(data, is.numeric)}
\NormalTok{categorical\_columns }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(data, is.character)}

\CommentTok{\# Replace missing values in numeric columns with the mean}
\NormalTok{data[numeric\_columns] }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(data[numeric\_columns], }\ControlFlowTok{function}\NormalTok{(column) \{}
  \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(column), }\FunctionTok{median}\NormalTok{(column, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), column)}
\NormalTok{\})}

\CommentTok{\# Replace missing values in categorical columns with the mode}
\NormalTok{data[categorical\_columns] }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(data[categorical\_columns], }\ControlFlowTok{function}\NormalTok{(column) \{}
\NormalTok{  column[}\FunctionTok{is.na}\NormalTok{(column)] }\OtherTok{\textless{}{-}} \FunctionTok{calculate\_mode}\NormalTok{(column)}
  \FunctionTok{return}\NormalTok{(column)}
\NormalTok{\})}

\CommentTok{\# Total number of missing values in the dataset}
\NormalTok{total\_missing }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(data))}

\CommentTok{\# Print the result}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Total number of missing values in the dataset:"}\NormalTok{, total\_missing))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Total number of missing values in the dataset: 0"
\end{verbatim}

Now there are no Missing Value in the dataset

\#Handling Outliers

\#Cap Outliers cap the values at the IQR thresholds

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{handle\_outliers\_iqr\_cap }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(data) \{}
\NormalTok{  numeric\_columns }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(data, is.numeric)  }\CommentTok{\# Identify numeric columns}
  
\NormalTok{  data[numeric\_columns] }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(data[numeric\_columns], }\ControlFlowTok{function}\NormalTok{(column) \{}
    \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{is.numeric}\NormalTok{(column)) \{}
\NormalTok{      Q1 }\OtherTok{\textless{}{-}} \FunctionTok{quantile}\NormalTok{(column, }\FloatTok{0.25}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{      Q3 }\OtherTok{\textless{}{-}} \FunctionTok{quantile}\NormalTok{(column, }\FloatTok{0.75}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{      IQR }\OtherTok{\textless{}{-}}\NormalTok{ Q3 }\SpecialCharTok{{-}}\NormalTok{ Q1}
\NormalTok{      lower\_bound }\OtherTok{\textless{}{-}}\NormalTok{ Q1 }\SpecialCharTok{{-}} \FloatTok{1.5} \SpecialCharTok{*}\NormalTok{ IQR}
\NormalTok{      upper\_bound }\OtherTok{\textless{}{-}}\NormalTok{ Q3 }\SpecialCharTok{+} \FloatTok{1.5} \SpecialCharTok{*}\NormalTok{ IQR}
      
      \CommentTok{\# Cap the values at lower and upper bounds}
\NormalTok{      column[column }\SpecialCharTok{\textless{}}\NormalTok{ lower\_bound] }\OtherTok{\textless{}{-}}\NormalTok{ lower\_bound}
\NormalTok{      column[column }\SpecialCharTok{\textgreater{}}\NormalTok{ upper\_bound] }\OtherTok{\textless{}{-}}\NormalTok{ upper\_bound}
\NormalTok{    \}}
    \FunctionTok{return}\NormalTok{(column)}
\NormalTok{  \})}
  
  \FunctionTok{return}\NormalTok{(data)}
\NormalTok{\}}

\CommentTok{\# Apply the capping method}
\NormalTok{data\_capped }\OtherTok{\textless{}{-}} \FunctionTok{handle\_outliers\_iqr\_cap}\NormalTok{(data)}

\CommentTok{\# Visualize boxplots again}
\FunctionTok{library}\NormalTok{(ggplot2)}
\NormalTok{numeric\_columns }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(data\_capped)[}\FunctionTok{sapply}\NormalTok{(data\_capped, is.numeric)]}
\ControlFlowTok{for}\NormalTok{ (column\_name }\ControlFlowTok{in}\NormalTok{ numeric\_columns) \{}
  \FunctionTok{print}\NormalTok{(}
    \FunctionTok{ggplot}\NormalTok{(data\_capped, }\FunctionTok{aes\_string}\NormalTok{(}\AttributeTok{y =}\NormalTok{ column\_name)) }\SpecialCharTok{+}
      \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{outlier.colour =} \StringTok{"red"}\NormalTok{, }\AttributeTok{outlier.shape =} \DecValTok{16}\NormalTok{, }\AttributeTok{outlier.size =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
      \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \FunctionTok{paste}\NormalTok{(}\StringTok{"Boxplot of"}\NormalTok{, column\_name, }\StringTok{"After Capping"}\NormalTok{), }\AttributeTok{y =}\NormalTok{ column\_name) }\SpecialCharTok{+}
      \FunctionTok{theme\_minimal}\NormalTok{()}
\NormalTok{  )}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: `aes_string()` was deprecated in ggplot2 3.0.0.
## i Please use tidy evaluation idioms with `aes()`.
## i See also `vignette("ggplot2-in-packages")` for more information.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-1.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-2.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-3.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-4.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-5.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-6.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-7.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-8.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-9.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-10.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-11.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-12.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-13.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-14.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-15.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-16.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-17.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-18.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-19.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-20.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-21.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-22.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-23.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-24.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-25.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-26.pdf}
\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-7-27.pdf}
Successfully Handled the Outliers

\#handeling Rare Values in Cat columns Identify Rare Categories

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#  threshold 0.5\%  for rare categories}
\NormalTok{threshold }\OtherTok{\textless{}{-}} \FloatTok{0.005}

\CommentTok{\# Identify rare categories for each categorical column}
\NormalTok{categorical\_columns }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(data, is.character)  }\CommentTok{\# Identify categorical columns}
\NormalTok{rare\_categories }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(data[, categorical\_columns], }\ControlFlowTok{function}\NormalTok{(column) \{}
\NormalTok{  freq\_table }\OtherTok{\textless{}{-}} \FunctionTok{prop.table}\NormalTok{(}\FunctionTok{table}\NormalTok{(column))}
  \FunctionTok{names}\NormalTok{(freq\_table[freq\_table }\SpecialCharTok{\textless{}}\NormalTok{ threshold])  }\CommentTok{\# Return rare categories}
\NormalTok{\})}

\CommentTok{\# Print rare categories for each column}
\NormalTok{rare\_categories}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $Program.Code
##  [1] "CN"  "CVP" "FN"  "HF"  "HH"  "HIS" "HO"  "HP"  "HW"  "HX"  "HY"  "HZ" 
## [13] "IK"  "SD" 
## 
## $Group.State
##  [1] "AB"             "AK"             "AR"             "Bermuda"       
##  [5] "Cayman Islands" "HI"             "ME"             "MS"            
##  [9] "MT"             "MX"             "ND"             "NH"            
## [13] "NJ"             "PA"             "PR"             "RI"            
## [17] "SC"             "SD"             "UT"             "VT"            
## [21] "WV"             "WY"            
## 
## $Travel.Type
## [1] "N" "T"
## 
## $Special.Pay
## character(0)
## 
## $Poverty.Code
## [1] "0"
## 
## $Region
## character(0)
## 
## $School.Type
## character(0)
## 
## $MDR.Low.Grade
## [1] "1"  "10" "2" 
## 
## $Income.Level
## [1] "P1" "P3" "P4" "P5"
## 
## $SPR.Product.Type
## [1] "IL History"
## 
## $SPR.New.Existing
## character(0)
## 
## $SchoolGradeTypeLow
## character(0)
## 
## $SchoolGradeTypeHigh
## character(0)
## 
## $SchoolGradeType
## [1] "Elementary->High"      "Elementary->Undefined"
## 
## $DepartureMonth
## [1] "January"
## 
## $GroupGradeTypeLow
## character(0)
## 
## $GroupGradeTypeHigh
## character(0)
## 
## $GroupGradeType
## [1] "Elementary->Elementary" "Elementary->High"      
## 
## $MajorProgramCode
## character(0)
## 
## $SchoolSizeIndicator
## character(0)
\end{verbatim}

Handle Rare Categories by group Rare Categories into ``Other'': Combine
rare categories into a single group labeled ``Other''.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Combine rare categories into "Other"}
\NormalTok{data[, categorical\_columns] }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(}\FunctionTok{names}\NormalTok{(data)[categorical\_columns], }\ControlFlowTok{function}\NormalTok{(col\_name) \{}
\NormalTok{  column }\OtherTok{\textless{}{-}}\NormalTok{ data[[col\_name]]}
\NormalTok{  freq\_table }\OtherTok{\textless{}{-}} \FunctionTok{prop.table}\NormalTok{(}\FunctionTok{table}\NormalTok{(column))}
\NormalTok{  rare\_values }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(freq\_table[freq\_table }\SpecialCharTok{\textless{}}\NormalTok{ threshold])}
\NormalTok{  column[column }\SpecialCharTok{\%in\%}\NormalTok{ rare\_values] }\OtherTok{\textless{}{-}} \StringTok{"Other"}
  \FunctionTok{return}\NormalTok{(column)}
\NormalTok{\})}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Check the frequency distribution after handling rare values}
\ControlFlowTok{for}\NormalTok{ (col\_name }\ControlFlowTok{in} \FunctionTok{names}\NormalTok{(data)[categorical\_columns]) \{}
  \FunctionTok{print}\NormalTok{(}\FunctionTok{table}\NormalTok{(data[[col\_name]]))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    CC    CD    HC    HD    HG    HN    HS   HVP    IC Other    SC    SG    SK 
##    14   114   274  1433    25    73   131    62    12    69    46    20    68 
##    SM    ST 
##    23    28 
## 
##    AL    AZ    CA    CO    CT    FL    GA    IA    ID    IL    IN    KS    KY 
##    21    53   721    89    15    62    22    35    14   104    43    26    16 
##    LA    MA    MD    MI    MN    MO    NC    NE    NM    NV    NY    OH    OK 
##    31    36    15    71    51    43    16    42    20    20    19    53    33 
##    OR Other    TN    TX    VA    WA    WI 
##    51   113    38   308    18   147    46 
## 
##     A     B Other 
##  2017   367     8 
## 
##   CP   FR   SA 
##   70 2215  107 
## 
##     A     B     C     D     E Other 
##   265  1563   507    36    17     4 
## 
##              Dallas             Houston Northern California               Other 
##                 163                 145                 275                1168 
##   Pacific Northwest Southern California 
##                 198                 443 
## 
##              Catholic                   CHD Private non-Christian 
##                   163                   257                   151 
##                PUBLIC 
##                  1821 
## 
##     3     4     5     6     7     8     9     K Other    PK 
##    12    17    96   959   348    14   104   428    13   401 
## 
##     A     B     C     D     E     F     G     H     I     J     K     L     M 
##    20    33    67    41    80   105    91    85   159   160   123   214   189 
##     N     O Other     P     Q     Z 
##   148   266     7   212   348    44 
## 
##    CA History    Costa Rica    East Coast International         Other 
##           175            46          2008            15             5 
##       Science 
##           143 
## 
## EXISTING      NEW 
##     1610      782 
## 
## Elementary       High     Middle  Undefined 
##        259        141       1865        127 
## 
## Elementary       High     Middle  Undefined 
##        196        265       1781        150 
## 
## Elementary->Elementary     Elementary->Middle             High->High 
##                    196                     57                    141 
##           Middle->High         Middle->Middle      Middle->Undefined 
##                    120                   1724                     21 
##                  Other   Undefined->Undefined 
##                      6                    127 
## 
##    April February     June    March      May    Other 
##      534       49      906      387      507        9 
## 
## Elementary       High          K     Middle         PK  Undefined 
##        135        107        428       1253        401         68 
## 
## Elementary       High     Middle  Undefined 
##        109        418       1797         68 
## 
##   Elementary->Middle           High->High        K->Elementary 
##                  120                  107                   71 
##              K->High            K->Middle         Middle->High 
##                   52                  305                  147 
##       Middle->Middle                Other       PK->Elementary 
##                 1106                   15                   31 
##             PK->High           PK->Middle Undefined->Undefined 
##                  104                  266                   68 
## 
##    C    H    I    S 
##  135 2052   16  189 
## 
##   L M-L   S S-M 
## 597 594 507 694
\end{verbatim}

\#Check Balance

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Check the class distribution of the target variable}
\FunctionTok{table}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1 
##  938 1454
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculate the proportion of each class}
\FunctionTok{prop.table}\NormalTok{(}\FunctionTok{table}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##         0         1 
## 0.3921405 0.6078595
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualize the class distribution}
\FunctionTok{library}\NormalTok{(ggplot2)}

\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{as.factor}\NormalTok{(Retained.in.}\FloatTok{2012.}\NormalTok{))) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{fill =} \StringTok{"skyblue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Class Distribution of Retained.in.2012."}\NormalTok{, }\AttributeTok{x =} \StringTok{"Class"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Count"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-11-1.pdf}
The dataset has some imbalance, but it is not severe (about a 60-40
split) and logistic regression, decision trees, and random forests can
handle mild imbalances reasonably well, However Algorithms like neural
networks may perform better with balanced data.Additionally because the
cost of misclassifying the minority class (0) is high and we must use
Evaluate performance like precision, recall, F1-score, and ROC-AUC, I
consider balancing.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Apply undersampling}
\NormalTok{downsampled\_data }\OtherTok{\textless{}{-}} \FunctionTok{downSample}\NormalTok{(}\AttributeTok{x =}\NormalTok{ data[, }\SpecialCharTok{{-}}\FunctionTok{which}\NormalTok{(}\FunctionTok{names}\NormalTok{(data) }\SpecialCharTok{==} \StringTok{"Retained.in.2012."}\NormalTok{)],}
                               \AttributeTok{y =} \FunctionTok{as.factor}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.}\NormalTok{))}

\CommentTok{\# Check the new class distribution}
\FunctionTok{table}\NormalTok{(downsampled\_data}\SpecialCharTok{$}\NormalTok{Class)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   0   1 
## 938 938
\end{verbatim}

Now the data is balanced

\#Normalization

I dicided to Normalize the data because there are some features with
large values (e.g., tuition) can dominate the model's calculations,
overshadowing features with smaller values (e.g., rates) to ensures that
all features contribute equally to the model.

I used Min-Max Normalization and In the his scales all features to a
range between {[}0, 1{]}:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Min{-}Max Normalization}
\NormalTok{normalize\_minmax }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) \{}
\NormalTok{  (x }\SpecialCharTok{{-}} \FunctionTok{min}\NormalTok{(x, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)) }\SpecialCharTok{/}\NormalTok{ (}\FunctionTok{max}\NormalTok{(x, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{{-}} \FunctionTok{min}\NormalTok{(x, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\NormalTok{\}}

\CommentTok{\# Apply normalization to numeric columns}
\NormalTok{numeric\_columns }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(data, is.numeric)}
\NormalTok{data[numeric\_columns] }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(data[numeric\_columns], normalize\_minmax)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    2392 obs. of  47 variables:
##  $ Program.Code                  : chr  "HS" "HC" "HD" "HN" ...
##  $ From.Grade                    : num  0.111 0.556 0.556 0.667 0.333 ...
##  $ To.Grade                      : num  0.111 0.556 0.556 1 0.556 ...
##  $ Group.State                   : chr  "CA" "AZ" "FL" "VA" ...
##  $ Is.Non.Annual.                : num  0 0 0 1 0 0 1 0 0 0 ...
##  $ Days                          : num  0 0.545 0.182 0.182 0.455 ...
##  $ Travel.Type                   : chr  "A" "A" "A" "B" ...
##  $ Special.Pay                   : chr  "FR" "CP" "FR" "FR" ...
##  $ Tuition                       : num  0.0837 0.5511 0.2674 0.0721 0.1907 ...
##  $ FRP.Active                    : num  0.0973 0.035 0.0661 0 0.1556 ...
##  $ FRP.Cancelled                 : num  0.0667 0.2 0.1333 0 0.1778 ...
##  $ FRP.Take.up.percent.          : num  0.424 0.409 0.708 0 0.494 0.9 0.64 0.769 0.577 0.773 ...
##  $ Cancelled.Pax                 : num  0.0769 0.2821 0.1538 0.0256 0.2308 ...
##  $ Total.Discount.Pax            : num  0.0851 0.0638 0.0638 0 0.1702 ...
##  $ Poverty.Code                  : chr  "B" "C" "C" "B" ...
##  $ Region                        : chr  "Southern California" "Other" "Other" "Other" ...
##  $ CRM.Segment                   : num  0.3 0.9 0.9 0.6 0.9 0.7 0.7 0.6 0.4 0.4 ...
##  $ School.Type                   : chr  "PUBLIC" "PUBLIC" "PUBLIC" "CHD" ...
##  $ Parent.Meeting.Flag           : num  1 1 1 0 1 1 1 1 1 1 ...
##  $ MDR.Low.Grade                 : chr  "K" "7" "6" "6" ...
##  $ MDR.High.Grade                : num  0.364 0.636 0.636 0.636 0.636 ...
##  $ Total.School.Enrollment       : num  0.229 0.209 0.236 0.146 0.177 ...
##  $ Income.Level                  : chr  "Q" "A" "O" "Q" ...
##  $ EZ.Pay.Take.Up.Rate           : num  0.0971 0.052 0.024 0 0.2189 ...
##  $ School.Sponsor                : num  1 0 0 0 0 0 0 0 0 0 ...
##  $ SPR.Product.Type              : chr  "CA History" "East Coast" "East Coast" "East Coast" ...
##  $ SPR.New.Existing              : chr  "EXISTING" "EXISTING" "EXISTING" "EXISTING" ...
##  $ FPP                           : num  0.2007 0.0704 0.0775 0.0563 0.2782 ...
##  $ Total.Pax                     : num  0.1961 0.074 0.0804 0.0514 0.2797 ...
##  $ SPR.Group.Revenue             : num  0.0837 0.5511 0.2674 0.0721 0.1907 ...
##  $ NumberOfMeetingswithParents   : num  0.5 1 0.5 0 0.5 0.5 0.5 0.5 0.5 0.5 ...
##  $ DifferenceTraveltoFirstMeeting: num  0.377 0.658 0.344 0.476 0.366 ...
##  $ DifferenceTraveltoLastMeeting : num  0.377 0.361 0.344 0.459 0.366 ...
##  $ SchoolGradeTypeLow            : chr  "Elementary" "Middle" "Middle" "High" ...
##  $ SchoolGradeTypeHigh           : chr  "Elementary" "Middle" "Middle" "High" ...
##  $ SchoolGradeType               : chr  "Elementary->Elementary" "Middle->Middle" "Middle->Middle" "High->High" ...
##  $ DepartureMonth                : chr  "Other" "Other" "Other" "Other" ...
##  $ GroupGradeTypeLow             : chr  "K" "Middle" "Middle" "Undefined" ...
##  $ GroupGradeTypeHigh            : chr  "Elementary" "Middle" "Middle" "Undefined" ...
##  $ GroupGradeType                : chr  "K->Elementary" "Middle->Middle" "Middle->Middle" "Undefined->Undefined" ...
##  $ MajorProgramCode              : chr  "H" "H" "H" "H" ...
##  $ SingleGradeTripFlag           : num  1 1 1 0 0 0 0 1 1 1 ...
##  $ FPP.to.School.enrollment      : num  0.0306 0.0122 0.0118 0.0216 0.0544 ...
##  $ FPP.to.PAX                    : num  0.841 0.7 0.722 1 0.775 ...
##  $ Num.of.Non_FPP.PAX            : num  0.0851 0.0638 0.0638 0 0.1702 ...
##  $ SchoolSizeIndicator           : chr  "L" "L" "L" "S-M" ...
##  $ Retained.in.2012.             : num  1 1 1 0 0 1 0 0 1 1 ...
\end{verbatim}

\#\#Correlations

Calculate Correlations:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Select only numeric columns (excluding the target variable)}
\NormalTok{numeric\_columns }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(data)[}\FunctionTok{sapply}\NormalTok{(data, is.numeric)]}
\NormalTok{numeric\_features }\OtherTok{\textless{}{-}}\NormalTok{ numeric\_columns[numeric\_columns }\SpecialCharTok{!=} \StringTok{"Retained.in.2012."}\NormalTok{]}

\CommentTok{\# Compute the correlation matrix}
\NormalTok{correlation\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(data[, numeric\_features], }\AttributeTok{use =} \StringTok{"pairwise.complete.obs"}\NormalTok{)}

\CommentTok{\# Find highly correlated pairs (correlation \textgreater{} 0.8 or \textless{} {-}0.8)}
\NormalTok{high\_corr\_pairs }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(}\FunctionTok{abs}\NormalTok{(correlation\_matrix) }\SpecialCharTok{\textgreater{}} \FloatTok{0.8}\NormalTok{, }\AttributeTok{arr.ind =} \ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# Exclude diagonal elements (self{-}correlations)}
\NormalTok{high\_corr\_pairs }\OtherTok{\textless{}{-}}\NormalTok{ high\_corr\_pairs[high\_corr\_pairs[, }\DecValTok{1}\NormalTok{] }\SpecialCharTok{!=}\NormalTok{ high\_corr\_pairs[, }\DecValTok{2}\NormalTok{], ]}

\CommentTok{\# Display the highly correlated pairs}
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{nrow}\NormalTok{(high\_corr\_pairs) }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"Highly correlated pairs:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
  \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(high\_corr\_pairs)) \{}
    \FunctionTok{cat}\NormalTok{(}\FunctionTok{rownames}\NormalTok{(correlation\_matrix)[high\_corr\_pairs[i, }\DecValTok{1}\NormalTok{]], }
        \StringTok{"and"}\NormalTok{, }
        \FunctionTok{colnames}\NormalTok{(correlation\_matrix)[high\_corr\_pairs[i, }\DecValTok{2}\NormalTok{]], }
        \StringTok{"with correlation:"}\NormalTok{, }
\NormalTok{        correlation\_matrix[high\_corr\_pairs[i, }\DecValTok{1}\NormalTok{], high\_corr\_pairs[i, }\DecValTok{2}\NormalTok{]], }
        \StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{  \}}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"No highly correlated pairs found.}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Highly correlated pairs:
## SPR.Group.Revenue and Tuition with correlation: 1 
## FPP and FRP.Active with correlation: 0.8153419 
## Total.Pax and FRP.Active with correlation: 0.8154766 
## Cancelled.Pax and FRP.Cancelled with correlation: 0.8503404 
## FRP.Cancelled and Cancelled.Pax with correlation: 0.8503404 
## FPP and Total.Discount.Pax with correlation: 0.8414566 
## Total.Pax and Total.Discount.Pax with correlation: 0.8670178 
## Num.of.Non_FPP.PAX and Total.Discount.Pax with correlation: 1 
## FRP.Active and FPP with correlation: 0.8153419 
## Total.Discount.Pax and FPP with correlation: 0.8414566 
## Total.Pax and FPP with correlation: 0.9987886 
## Num.of.Non_FPP.PAX and FPP with correlation: 0.8414566 
## FRP.Active and Total.Pax with correlation: 0.8154766 
## Total.Discount.Pax and Total.Pax with correlation: 0.8670178 
## FPP and Total.Pax with correlation: 0.9987886 
## Num.of.Non_FPP.PAX and Total.Pax with correlation: 0.8670178 
## Tuition and SPR.Group.Revenue with correlation: 1 
## Total.Discount.Pax and Num.of.Non_FPP.PAX with correlation: 1 
## FPP and Num.of.Non_FPP.PAX with correlation: 0.8414566 
## Total.Pax and Num.of.Non_FPP.PAX with correlation: 0.8670178
\end{verbatim}

Other Variables Correlation with the Target Variable
``Retained.in.2012.''

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Compute correlations of numeric features with the target variable}
\NormalTok{target\_correlations }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(numeric\_features, }\ControlFlowTok{function}\NormalTok{(col) \{}
  \FunctionTok{cor}\NormalTok{(data[[col]], data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.}\NormalTok{, }\AttributeTok{use =} \StringTok{"pairwise.complete.obs"}\NormalTok{)}
\NormalTok{\})}

\CommentTok{\# Sort features by their correlation with the target variable}
\NormalTok{sorted\_correlations }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(}\FunctionTok{abs}\NormalTok{(target\_correlations), }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# Display correlations with the target}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Correlation with Retained.in.2012.:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Correlation with Retained.in.2012.:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(sorted\_correlations)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            SingleGradeTripFlag                 Is.Non.Annual. 
##                    0.456358952                    0.390860429 
##                            FPP                      Total.Pax 
##                    0.260720974                    0.260111811 
##                     FRP.Active             Total.Discount.Pax 
##                    0.250074118                    0.215781071 
##             Num.of.Non_FPP.PAX                       To.Grade 
##                    0.215781071                    0.193973455 
##                     FPP.to.PAX                 MDR.High.Grade 
##                    0.145218861                    0.132413543 
## DifferenceTraveltoFirstMeeting                 School.Sponsor 
##                    0.121966573                    0.120312743 
##                        Tuition              SPR.Group.Revenue 
##                    0.118832808                    0.118832808 
##  DifferenceTraveltoLastMeeting        Total.School.Enrollment 
##                    0.095429993                    0.084142912 
##                     From.Grade                  FRP.Cancelled 
##                    0.077450617                    0.072265586 
##       FPP.to.School.enrollment    NumberOfMeetingswithParents 
##                    0.070194405                    0.052294928 
##                           Days                  Cancelled.Pax 
##                    0.049080333                    0.048802170 
##            Parent.Meeting.Flag            EZ.Pay.Take.Up.Rate 
##                    0.020062524                    0.018103739 
##           FRP.Take.up.percent.                    CRM.Segment 
##                    0.016530292                    0.008824892
\end{verbatim}

Visualize Correlations

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Melt the correlation matrix for visualization}
\NormalTok{correlation\_melted }\OtherTok{\textless{}{-}} \FunctionTok{melt}\NormalTok{(correlation\_matrix)}

\CommentTok{\# Plot the heatmap}
\FunctionTok{ggplot}\NormalTok{(correlation\_melted, }\FunctionTok{aes}\NormalTok{(Var1, Var2, }\AttributeTok{fill =}\NormalTok{ value)) }\SpecialCharTok{+}
  \FunctionTok{geom\_tile}\NormalTok{(}\AttributeTok{color =} \StringTok{"white"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_gradient2}\NormalTok{(}\AttributeTok{low =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{high =} \StringTok{"red"}\NormalTok{, }\AttributeTok{mid =} \StringTok{"white"}\NormalTok{, }\AttributeTok{midpoint =} \DecValTok{0}\NormalTok{, }\AttributeTok{limit =} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{), }\AttributeTok{space =} \StringTok{"Lab"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Feature Correlation Heatmap"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Features"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Features"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-17-1.pdf}
\#Remove Highly Correlated Features

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Keep only one feature from each highly correlated pair based on target correlation}
\NormalTok{features\_to\_remove }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{()}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(high\_corr\_pairs)) \{}
\NormalTok{  feature1 }\OtherTok{\textless{}{-}} \FunctionTok{rownames}\NormalTok{(correlation\_matrix)[high\_corr\_pairs[i, }\DecValTok{1}\NormalTok{]]}
\NormalTok{  feature2 }\OtherTok{\textless{}{-}} \FunctionTok{colnames}\NormalTok{(correlation\_matrix)[high\_corr\_pairs[i, }\DecValTok{2}\NormalTok{]]}
  
  \CommentTok{\# Compare correlations with the target and decide which to keep}
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{abs}\NormalTok{(target\_correlations[feature1]) }\SpecialCharTok{\textgreater{}=} \FunctionTok{abs}\NormalTok{(target\_correlations[feature2])) \{}
\NormalTok{    features\_to\_remove }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(features\_to\_remove, feature2)}
\NormalTok{  \} }\ControlFlowTok{else}\NormalTok{ \{}
\NormalTok{    features\_to\_remove }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(features\_to\_remove, feature1)}
\NormalTok{  \}}
\NormalTok{\}}

\CommentTok{\# Remove Duplicates}
\NormalTok{features\_to\_remove }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(features\_to\_remove)}

\CommentTok{\# Drop Features from the Dataset}
\NormalTok{data }\OtherTok{\textless{}{-}}\NormalTok{ data[, }\SpecialCharTok{!}\FunctionTok{names}\NormalTok{(data) }\SpecialCharTok{\%in\%}\NormalTok{ features\_to\_remove]}

\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Removed features due to high correlation:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Removed features due to high correlation:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(features\_to\_remove)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Tuition"            "FRP.Active"         "Cancelled.Pax"     
## [4] "Total.Discount.Pax" "Total.Pax"          "Num.of.Non_FPP.PAX"
## [7] "SPR.Group.Revenue"
\end{verbatim}

\#Drop Low Correlation Features

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Drop features with low correlation to the target variable}
\NormalTok{low\_correlation\_features }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(sorted\_correlations[sorted\_correlations }\SpecialCharTok{\textless{}} \FloatTok{0.1}\NormalTok{])}
\NormalTok{low\_correlation\_features}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "DifferenceTraveltoLastMeeting" "Total.School.Enrollment"      
##  [3] "From.Grade"                    "FRP.Cancelled"                
##  [5] "FPP.to.School.enrollment"      "NumberOfMeetingswithParents"  
##  [7] "Days"                          "Cancelled.Pax"                
##  [9] "Parent.Meeting.Flag"           "EZ.Pay.Take.Up.Rate"          
## [11] "FRP.Take.up.percent."          "CRM.Segment"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{\textless{}{-}}\NormalTok{ data[, }\SpecialCharTok{!}\FunctionTok{names}\NormalTok{(data) }\SpecialCharTok{\%in\%}\NormalTok{ low\_correlation\_features]}
\end{Highlighting}
\end{Shaded}

\#Corelations after dropping

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Select only numeric columns (excluding the target variable)}
\NormalTok{numeric\_columns }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(data)[}\FunctionTok{sapply}\NormalTok{(data, is.numeric)]}
\NormalTok{numeric\_features }\OtherTok{\textless{}{-}}\NormalTok{ numeric\_columns[numeric\_columns }\SpecialCharTok{!=} \StringTok{"Retained.in.2012."}\NormalTok{]}

\CommentTok{\# Compute the correlation matrix}
\NormalTok{correlation\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(data[, numeric\_features], }\AttributeTok{use =} \StringTok{"pairwise.complete.obs"}\NormalTok{)}

\CommentTok{\# Find highly correlated pairs (correlation \textgreater{} 0.8 or \textless{} {-}0.8)}
\NormalTok{high\_corr\_pairs }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(}\FunctionTok{abs}\NormalTok{(correlation\_matrix) }\SpecialCharTok{\textgreater{}} \FloatTok{0.8}\NormalTok{, }\AttributeTok{arr.ind =} \ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# Exclude diagonal elements (self{-}correlations)}
\NormalTok{high\_corr\_pairs }\OtherTok{\textless{}{-}}\NormalTok{ high\_corr\_pairs[high\_corr\_pairs[, }\DecValTok{1}\NormalTok{] }\SpecialCharTok{!=}\NormalTok{ high\_corr\_pairs[, }\DecValTok{2}\NormalTok{], ]}

\CommentTok{\# Display the highly correlated pairs}
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{nrow}\NormalTok{(high\_corr\_pairs) }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"Highly correlated pairs:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
  \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(high\_corr\_pairs)) \{}
    \FunctionTok{cat}\NormalTok{(}\FunctionTok{rownames}\NormalTok{(correlation\_matrix)[high\_corr\_pairs[i, }\DecValTok{1}\NormalTok{]], }
        \StringTok{"and"}\NormalTok{, }
        \FunctionTok{colnames}\NormalTok{(correlation\_matrix)[high\_corr\_pairs[i, }\DecValTok{2}\NormalTok{]], }
        \StringTok{"with correlation:"}\NormalTok{, }
\NormalTok{        correlation\_matrix[high\_corr\_pairs[i, }\DecValTok{1}\NormalTok{], high\_corr\_pairs[i, }\DecValTok{2}\NormalTok{]], }
        \StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{  \}}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"No highly correlated pairs found.}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## No highly correlated pairs found.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Compute correlations of numeric features with the target variable}
\NormalTok{target\_correlations }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(numeric\_features, }\ControlFlowTok{function}\NormalTok{(col) \{}
  \FunctionTok{cor}\NormalTok{(data[[col]], data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.}\NormalTok{, }\AttributeTok{use =} \StringTok{"pairwise.complete.obs"}\NormalTok{)}
\NormalTok{\})}

\CommentTok{\# Sort features by their correlation with the target variable}
\NormalTok{sorted\_correlations }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(}\FunctionTok{abs}\NormalTok{(target\_correlations), }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# Display correlations with the target}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Correlation with Retained.in.2012.:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Correlation with Retained.in.2012.:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(sorted\_correlations)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            SingleGradeTripFlag                 Is.Non.Annual. 
##                      0.4563590                      0.3908604 
##                            FPP                       To.Grade 
##                      0.2607210                      0.1939735 
##                     FPP.to.PAX                 MDR.High.Grade 
##                      0.1452189                      0.1324135 
## DifferenceTraveltoFirstMeeting                 School.Sponsor 
##                      0.1219666                      0.1203127
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Melt the correlation matrix for visualization}
\NormalTok{correlation\_melted }\OtherTok{\textless{}{-}} \FunctionTok{melt}\NormalTok{(correlation\_matrix)}

\CommentTok{\# Plot the heatmap}
\FunctionTok{ggplot}\NormalTok{(correlation\_melted, }\FunctionTok{aes}\NormalTok{(Var1, Var2, }\AttributeTok{fill =}\NormalTok{ value)) }\SpecialCharTok{+}
  \FunctionTok{geom\_tile}\NormalTok{(}\AttributeTok{color =} \StringTok{"white"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_gradient2}\NormalTok{(}\AttributeTok{low =} \StringTok{"green"}\NormalTok{, }\AttributeTok{high =} \StringTok{"orange"}\NormalTok{, }\AttributeTok{mid =} \StringTok{"white"}\NormalTok{, }\AttributeTok{midpoint =} \DecValTok{0}\NormalTok{, }\AttributeTok{limit =} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{), }\AttributeTok{space =} \StringTok{"Lab"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Feature Correlation Heatmap"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Features"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Features"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-20-1.pdf}

\#Correlation with the Target Variable after remove high and low
corelation variables

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Compute correlations of numeric features with the target variable}
\NormalTok{target\_correlations }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(numeric\_features, }\ControlFlowTok{function}\NormalTok{(col) \{}
  \FunctionTok{cor}\NormalTok{(data[[col]], data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.}\NormalTok{, }\AttributeTok{use =} \StringTok{"pairwise.complete.obs"}\NormalTok{)}
\NormalTok{\})}

\CommentTok{\# Sort features by their correlation with the target variable}
\NormalTok{sorted\_correlations }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(}\FunctionTok{abs}\NormalTok{(target\_correlations), }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# Display correlations with the target}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Correlation with Retained.in.2012.:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Correlation with Retained.in.2012.:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(sorted\_correlations)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            SingleGradeTripFlag                 Is.Non.Annual. 
##                      0.4563590                      0.3908604 
##                            FPP                       To.Grade 
##                      0.2607210                      0.1939735 
##                     FPP.to.PAX                 MDR.High.Grade 
##                      0.1452189                      0.1324135 
## DifferenceTraveltoFirstMeeting                 School.Sponsor 
##                      0.1219666                      0.1203127
\end{verbatim}

\#Univariate Analysis

Descriptive Statistics

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Descriptive statistics for numeric variables}
\FunctionTok{summary}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Program.Code          To.Grade      Group.State        Is.Non.Annual.  
##  Length:2392        Min.   :0.0000   Length:2392        Min.   :0.0000  
##  Class :character   1st Qu.:0.5556   Class :character   1st Qu.:0.0000  
##  Mode  :character   Median :0.5556   Mode  :character   Median :0.0000  
##                     Mean   :0.5465                      Mean   :0.1538  
##                     3rd Qu.:0.5556                      3rd Qu.:0.0000  
##                     Max.   :1.0000                      Max.   :1.0000  
##  Travel.Type        Special.Pay        Poverty.Code          Region         
##  Length:2392        Length:2392        Length:2392        Length:2392       
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##  School.Type        MDR.Low.Grade      MDR.High.Grade   Income.Level      
##  Length:2392        Length:2392        Min.   :0.0000   Length:2392       
##  Class :character   Class :character   1st Qu.:0.6364   Class :character  
##  Mode  :character   Mode  :character   Median :0.6364   Mode  :character  
##                                        Mean   :0.6709                     
##                                        3rd Qu.:0.6364                     
##                                        Max.   :1.0000                     
##  School.Sponsor   SPR.Product.Type   SPR.New.Existing        FPP         
##  Min.   :0.0000   Length:2392        Length:2392        Min.   :0.00000  
##  1st Qu.:0.0000   Class :character   Class :character   1st Qu.:0.03521  
##  Median :0.0000   Mode  :character   Mode  :character   Median :0.07394  
##  Mean   :0.1058                                         Mean   :0.10312  
##  3rd Qu.:0.0000                                         3rd Qu.:0.13732  
##  Max.   :1.0000                                         Max.   :1.00000  
##  DifferenceTraveltoFirstMeeting SchoolGradeTypeLow SchoolGradeTypeHigh
##  Min.   :0.0000                 Length:2392        Length:2392        
##  1st Qu.:0.4407                 Class :character   Class :character   
##  Median :0.4764                 Mode  :character   Mode  :character   
##  Mean   :0.4873                                                       
##  3rd Qu.:0.5047                                                       
##  Max.   :1.0000                                                       
##  SchoolGradeType    DepartureMonth     GroupGradeTypeLow  GroupGradeTypeHigh
##  Length:2392        Length:2392        Length:2392        Length:2392       
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##  GroupGradeType     MajorProgramCode   SingleGradeTripFlag   FPP.to.PAX    
##  Length:2392        Length:2392        Min.   :0.0000      Min.   :0.0000  
##  Class :character   Class :character   1st Qu.:0.0000      1st Qu.:0.7059  
##  Mode  :character   Mode  :character   Median :1.0000      Median :0.7727  
##                                        Mean   :0.5573      Mean   :0.7517  
##                                        3rd Qu.:1.0000      3rd Qu.:0.8333  
##                                        Max.   :1.0000      Max.   :1.0000  
##  SchoolSizeIndicator Retained.in.2012.
##  Length:2392         Min.   :0.0000   
##  Class :character    1st Qu.:0.0000   
##  Mode  :character    Median :1.0000   
##                      Mean   :0.6079   
##                      3rd Qu.:1.0000   
##                      Max.   :1.0000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# View unique values for categorical variables}
\FunctionTok{sapply}\NormalTok{(data, }\ControlFlowTok{function}\NormalTok{(col) }\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{is.factor}\NormalTok{(col) }\SpecialCharTok{||} \FunctionTok{is.character}\NormalTok{(col)) }\FunctionTok{unique}\NormalTok{(col))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $Program.Code
##  [1] "HS"    "HC"    "HD"    "HN"    "SG"    "Other" "CC"    "CD"    "HVP"  
## [10] "SM"    "HG"    "SK"    "SC"    "IC"    "ST"   
## 
## $To.Grade
## NULL
## 
## $Group.State
##  [1] "CA"    "AZ"    "FL"    "VA"    "LA"    "MA"    "Other" "TX"    "IA"   
## [10] "MI"    "NY"    "NC"    "OH"    "MN"    "IL"    "IN"    "WI"    "MO"   
## [19] "ID"    "TN"    "KS"    "AL"    "KY"    "OR"    "NE"    "CO"    "NM"   
## [28] "OK"    "GA"    "WA"    "NV"    "CT"    "MD"   
## 
## $Is.Non.Annual.
## NULL
## 
## $Travel.Type
## [1] "A"     "B"     "Other"
## 
## $Special.Pay
## [1] "FR" "CP" "SA"
## 
## $Poverty.Code
## [1] "B"     "C"     "D"     "A"     "E"     "Other"
## 
## $Region
## [1] "Southern California" "Other"               "Houston"            
## [4] "Northern California" "Dallas"              "Pacific Northwest"  
## 
## $School.Type
## [1] "PUBLIC"                "CHD"                   "Catholic"             
## [4] "Private non-Christian"
## 
## $MDR.Low.Grade
##  [1] "K"     "7"     "6"     "Other" "9"     "PK"    "5"     "3"     "4"    
## [10] "8"    
## 
## $MDR.High.Grade
## NULL
## 
## $Income.Level
##  [1] "Q"     "A"     "O"     "C"     "I"     "G"     "K"     "L"     "Other"
## [10] "N"     "H"     "E"     "M"     "P"     "J"     "Z"     "B"     "F"    
## [19] "D"    
## 
## $School.Sponsor
## NULL
## 
## $SPR.Product.Type
## [1] "CA History"    "East Coast"    "Science"       "Costa Rica"   
## [5] "International" "Other"        
## 
## $SPR.New.Existing
## [1] "EXISTING" "NEW"     
## 
## $FPP
## NULL
## 
## $DifferenceTraveltoFirstMeeting
## NULL
## 
## $SchoolGradeTypeLow
## [1] "Elementary" "Middle"     "High"       "Undefined" 
## 
## $SchoolGradeTypeHigh
## [1] "Elementary" "Middle"     "High"       "Undefined" 
## 
## $SchoolGradeType
## [1] "Elementary->Elementary" "Middle->Middle"         "High->High"            
## [4] "Undefined->Undefined"   "Middle->Undefined"      "Elementary->Middle"    
## [7] "Middle->High"           "Other"                 
## 
## $DepartureMonth
## [1] "Other"    "February" "March"    "April"    "May"      "June"    
## 
## $GroupGradeTypeLow
## [1] "K"          "Middle"     "Undefined"  "High"       "PK"        
## [6] "Elementary"
## 
## $GroupGradeTypeHigh
## [1] "Elementary" "Middle"     "Undefined"  "High"      
## 
## $GroupGradeType
##  [1] "K->Elementary"        "Middle->Middle"       "Undefined->Undefined"
##  [4] "High->High"           "Middle->High"         "PK->Middle"          
##  [7] "K->High"              "Elementary->Middle"   "PK->High"            
## [10] "K->Middle"            "Other"                "PK->Elementary"      
## 
## $MajorProgramCode
## [1] "H" "S" "I" "C"
## 
## $SingleGradeTripFlag
## NULL
## 
## $FPP.to.PAX
## NULL
## 
## $SchoolSizeIndicator
## [1] "L"   "S-M" "M-L" "S"  
## 
## $Retained.in.2012.
## NULL
\end{verbatim}

Visualizing Distributions For Numeric Variables: Use histograms or
density plots.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Identify numeric and character columns}
\NormalTok{numeric\_columns }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(data)[}\FunctionTok{sapply}\NormalTok{(data, is.numeric)]}
\NormalTok{character\_columns }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(data)[}\FunctionTok{sapply}\NormalTok{(data, is.character)]}

\CommentTok{\# Step 1: Process Numeric Columns (e.g., Histograms, Descriptive Statistics)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Processing Numeric Columns:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Processing Numeric Columns:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{ (col\_name }\ControlFlowTok{in}\NormalTok{ numeric\_columns) \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Summary of"}\NormalTok{, col\_name, }\StringTok{":}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
  \FunctionTok{print}\NormalTok{(}\FunctionTok{summary}\NormalTok{(data[[col\_name]]))  }\CommentTok{\# Print summary statistics}
  
  \CommentTok{\# Plot histogram}
  \FunctionTok{print}\NormalTok{(}
    \FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes\_string}\NormalTok{(}\AttributeTok{x =}\NormalTok{ col\_name)) }\SpecialCharTok{+}
      \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{fill =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{bins =} \DecValTok{30}\NormalTok{) }\SpecialCharTok{+}
      \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \FunctionTok{paste}\NormalTok{(}\StringTok{"Histogram of"}\NormalTok{, col\_name), }\AttributeTok{x =}\NormalTok{ col\_name, }\AttributeTok{y =} \StringTok{"Frequency"}\NormalTok{) }\SpecialCharTok{+}
      \FunctionTok{theme\_minimal}\NormalTok{()}
\NormalTok{  )}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Summary of To.Grade :
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  0.5556  0.5556  0.5465  0.5556  1.0000
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-1.pdf}

\begin{verbatim}
## 
## Summary of Is.Non.Annual. :
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  0.0000  0.0000  0.1538  0.0000  1.0000
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-2.pdf}

\begin{verbatim}
## 
## Summary of MDR.High.Grade :
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  0.6364  0.6364  0.6709  0.6364  1.0000
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-3.pdf}

\begin{verbatim}
## 
## Summary of School.Sponsor :
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  0.0000  0.0000  0.1058  0.0000  1.0000
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-4.pdf}

\begin{verbatim}
## 
## Summary of FPP :
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## 0.00000 0.03521 0.07394 0.10312 0.13732 1.00000
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-5.pdf}

\begin{verbatim}
## 
## Summary of DifferenceTraveltoFirstMeeting :
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  0.4407  0.4764  0.4873  0.5047  1.0000
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-6.pdf}

\begin{verbatim}
## 
## Summary of SingleGradeTripFlag :
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  0.0000  1.0000  0.5573  1.0000  1.0000
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-7.pdf}

\begin{verbatim}
## 
## Summary of FPP.to.PAX :
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  0.7059  0.7727  0.7517  0.8333  1.0000
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-8.pdf}

\begin{verbatim}
## 
## Summary of Retained.in.2012. :
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  0.0000  1.0000  0.6079  1.0000  1.0000
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-9.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Step 2: Process Character Columns (e.g., Frequency Counts, Bar Plots)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Processing Character Columns:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Processing Character Columns:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{ (col\_name }\ControlFlowTok{in}\NormalTok{ character\_columns) \{}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Frequency Table of"}\NormalTok{, col\_name, }\StringTok{":}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
  \FunctionTok{print}\NormalTok{(}\FunctionTok{table}\NormalTok{(data[[col\_name]], }\AttributeTok{useNA =} \StringTok{"ifany"}\NormalTok{))  }\CommentTok{\# Print frequency table}
  
  \CommentTok{\# Plot bar chart}
  \FunctionTok{print}\NormalTok{(}
    \FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes\_string}\NormalTok{(}\AttributeTok{x =}\NormalTok{ col\_name)) }\SpecialCharTok{+}
      \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{fill =} \StringTok{"green"}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{+}
      \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \FunctionTok{paste}\NormalTok{(}\StringTok{"Bar Plot of"}\NormalTok{, col\_name), }\AttributeTok{x =}\NormalTok{ col\_name, }\AttributeTok{y =} \StringTok{"Count"}\NormalTok{) }\SpecialCharTok{+}
      \FunctionTok{theme\_minimal}\NormalTok{()}
\NormalTok{  )}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Frequency Table of Program.Code :
## 
##    CC    CD    HC    HD    HG    HN    HS   HVP    IC Other    SC    SG    SK 
##    14   114   274  1433    25    73   131    62    12    69    46    20    68 
##    SM    ST 
##    23    28
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-10.pdf}

\begin{verbatim}
## 
## Frequency Table of Group.State :
## 
##    AL    AZ    CA    CO    CT    FL    GA    IA    ID    IL    IN    KS    KY 
##    21    53   721    89    15    62    22    35    14   104    43    26    16 
##    LA    MA    MD    MI    MN    MO    NC    NE    NM    NV    NY    OH    OK 
##    31    36    15    71    51    43    16    42    20    20    19    53    33 
##    OR Other    TN    TX    VA    WA    WI 
##    51   113    38   308    18   147    46
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-11.pdf}

\begin{verbatim}
## 
## Frequency Table of Travel.Type :
## 
##     A     B Other 
##  2017   367     8
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-12.pdf}

\begin{verbatim}
## 
## Frequency Table of Special.Pay :
## 
##   CP   FR   SA 
##   70 2215  107
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-13.pdf}

\begin{verbatim}
## 
## Frequency Table of Poverty.Code :
## 
##     A     B     C     D     E Other 
##   265  1563   507    36    17     4
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-14.pdf}

\begin{verbatim}
## 
## Frequency Table of Region :
## 
##              Dallas             Houston Northern California               Other 
##                 163                 145                 275                1168 
##   Pacific Northwest Southern California 
##                 198                 443
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-15.pdf}

\begin{verbatim}
## 
## Frequency Table of School.Type :
## 
##              Catholic                   CHD Private non-Christian 
##                   163                   257                   151 
##                PUBLIC 
##                  1821
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-16.pdf}

\begin{verbatim}
## 
## Frequency Table of MDR.Low.Grade :
## 
##     3     4     5     6     7     8     9     K Other    PK 
##    12    17    96   959   348    14   104   428    13   401
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-17.pdf}

\begin{verbatim}
## 
## Frequency Table of Income.Level :
## 
##     A     B     C     D     E     F     G     H     I     J     K     L     M 
##    20    33    67    41    80   105    91    85   159   160   123   214   189 
##     N     O Other     P     Q     Z 
##   148   266     7   212   348    44
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-18.pdf}

\begin{verbatim}
## 
## Frequency Table of SPR.Product.Type :
## 
##    CA History    Costa Rica    East Coast International         Other 
##           175            46          2008            15             5 
##       Science 
##           143
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-19.pdf}

\begin{verbatim}
## 
## Frequency Table of SPR.New.Existing :
## 
## EXISTING      NEW 
##     1610      782
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-20.pdf}

\begin{verbatim}
## 
## Frequency Table of SchoolGradeTypeLow :
## 
## Elementary       High     Middle  Undefined 
##        259        141       1865        127
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-21.pdf}

\begin{verbatim}
## 
## Frequency Table of SchoolGradeTypeHigh :
## 
## Elementary       High     Middle  Undefined 
##        196        265       1781        150
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-22.pdf}

\begin{verbatim}
## 
## Frequency Table of SchoolGradeType :
## 
## Elementary->Elementary     Elementary->Middle             High->High 
##                    196                     57                    141 
##           Middle->High         Middle->Middle      Middle->Undefined 
##                    120                   1724                     21 
##                  Other   Undefined->Undefined 
##                      6                    127
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-23.pdf}

\begin{verbatim}
## 
## Frequency Table of DepartureMonth :
## 
##    April February     June    March      May    Other 
##      534       49      906      387      507        9
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-24.pdf}

\begin{verbatim}
## 
## Frequency Table of GroupGradeTypeLow :
## 
## Elementary       High          K     Middle         PK  Undefined 
##        135        107        428       1253        401         68
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-25.pdf}

\begin{verbatim}
## 
## Frequency Table of GroupGradeTypeHigh :
## 
## Elementary       High     Middle  Undefined 
##        109        418       1797         68
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-26.pdf}

\begin{verbatim}
## 
## Frequency Table of GroupGradeType :
## 
##   Elementary->Middle           High->High        K->Elementary 
##                  120                  107                   71 
##              K->High            K->Middle         Middle->High 
##                   52                  305                  147 
##       Middle->Middle                Other       PK->Elementary 
##                 1106                   15                   31 
##             PK->High           PK->Middle Undefined->Undefined 
##                  104                  266                   68
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-27.pdf}

\begin{verbatim}
## 
## Frequency Table of MajorProgramCode :
## 
##    C    H    I    S 
##  135 2052   16  189
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-28.pdf}

\begin{verbatim}
## 
## Frequency Table of SchoolSizeIndicator :
## 
##   L M-L   S S-M 
## 597 594 507 694
\end{verbatim}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-23-29.pdf}
\#Multivariate Analysis Correlation Analysis Computed pairwise
correlations between numeric variables.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Correlation matrix}
\NormalTok{correlation\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(data[}\FunctionTok{sapply}\NormalTok{(data, is.numeric)], }\AttributeTok{use =} \StringTok{"pairwise.complete.obs"}\NormalTok{)}

\CommentTok{\# Heatmap for visualization}
\FunctionTok{library}\NormalTok{(reshape2)}
\NormalTok{correlation\_melted }\OtherTok{\textless{}{-}} \FunctionTok{melt}\NormalTok{(correlation\_matrix)}
\FunctionTok{ggplot}\NormalTok{(correlation\_melted, }\FunctionTok{aes}\NormalTok{(Var1, Var2, }\AttributeTok{fill =}\NormalTok{ value)) }\SpecialCharTok{+}
  \FunctionTok{geom\_tile}\NormalTok{(}\AttributeTok{color =} \StringTok{"white"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_gradient2}\NormalTok{(}\AttributeTok{low =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{high =} \StringTok{"red"}\NormalTok{, }\AttributeTok{mid =} \StringTok{"white"}\NormalTok{, }\AttributeTok{midpoint =} \DecValTok{0}\NormalTok{, }\AttributeTok{limit =} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Correlation Heatmap"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Features"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Features"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-24-1.pdf}
\#Scatter Plots relationships between ``two numeric
variables''DifferenceTraveltoFirstMeeting'' and ``Retained.in.2012.''.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Scatter plot for two numeric variables}
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ DifferenceTraveltoFirstMeeting, }\AttributeTok{y =}\NormalTok{ Retained.in.}\FloatTok{2012.}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{color =} \StringTok{"blue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Scatter Plot"}\NormalTok{, }\AttributeTok{x =} \StringTok{"DifferenceTraveltoFirstMeeting"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Retained.in.2012."}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-25-1.pdf}

Inferential Statistics

\#T\_test T-Test for All Numeric Variables

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Ensure the target variable is a factor (required for grouping in t{-}test)}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.} \OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.}\NormalTok{)}

\CommentTok{\# Identify numeric columns}
\NormalTok{numeric\_columns }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(data)[}\FunctionTok{sapply}\NormalTok{(data, is.numeric)]}

\CommentTok{\# Perform T{-}test for each numeric column}
\NormalTok{t\_test\_results }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(numeric\_columns, }\ControlFlowTok{function}\NormalTok{(col) \{}
\NormalTok{  test }\OtherTok{\textless{}{-}} \FunctionTok{t.test}\NormalTok{(data[[col]] }\SpecialCharTok{\textasciitilde{}}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.}\NormalTok{, }\AttributeTok{data =}\NormalTok{ data)}
  \FunctionTok{list}\NormalTok{(}
    \AttributeTok{Variable =}\NormalTok{ col,}
    \AttributeTok{P\_Value =}\NormalTok{ test}\SpecialCharTok{$}\NormalTok{p.value,}
    \AttributeTok{Mean\_Group\_0 =}\NormalTok{ test}\SpecialCharTok{$}\NormalTok{estimate[}\DecValTok{1}\NormalTok{],}
    \AttributeTok{Mean\_Group\_1 =}\NormalTok{ test}\SpecialCharTok{$}\NormalTok{estimate[}\DecValTok{2}\NormalTok{]}
\NormalTok{  )}
\NormalTok{\})}

\CommentTok{\# Convert results to a data frame for easy interpretation}
\NormalTok{t\_test\_summary }\OtherTok{\textless{}{-}} \FunctionTok{do.call}\NormalTok{(rbind, }\FunctionTok{lapply}\NormalTok{(t\_test\_results, as.data.frame))}
\NormalTok{t\_test\_summary }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(t\_test\_summary)}

\CommentTok{\# View results}
\FunctionTok{print}\NormalTok{(t\_test\_summary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                                        Variable       P_Value Mean_Group_0
## mean in group 0                        To.Grade  1.487033e-19   0.58694622
## mean in group 01                 Is.Non.Annual.  5.744928e-63   0.32942431
## mean in group 02                 MDR.High.Grade  8.336857e-10   0.69674355
## mean in group 03                 School.Sponsor  1.949151e-10   0.05970149
## mean in group 04                            FPP  8.938922e-46   0.06985195
## mean in group 05 DifferenceTraveltoFirstMeeting  1.074000e-08   0.49902004
## mean in group 06            SingleGradeTripFlag 6.537768e-120   0.27505330
## mean in group 07                     FPP.to.PAX  1.118602e-11   0.72950926
##                  Mean_Group_1
## mean in group 0    0.52040348
## mean in group 01   0.04057772
## mean in group 02   0.65430787
## mean in group 03   0.13548831
## mean in group 04   0.12458589
## mean in group 05   0.47968624
## mean in group 06   0.73933975
## mean in group 07   0.76600407
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Save results to a CSV file}
\FunctionTok{write.csv}\NormalTok{(t\_test\_summary, }\StringTok{"T\_Test\_Results.csv"}\NormalTok{, }\AttributeTok{row.names =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Based on the low p-values, variables like To.Grade, Is.Non.Annual., FPP,
and SingleGradeTripFlag should be considered important predictors in
further modeling or analysis.Variables with the largest mean differences
(e.g., SingleGradeTripFlag, FPP) might have the strongest
influence.Since all variables have significant p-values, I retain them
all for modeling.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Perform ANOVA for each numeric column}
\NormalTok{anova\_results }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(numeric\_columns, }\ControlFlowTok{function}\NormalTok{(col) \{}
\NormalTok{  formula }\OtherTok{\textless{}{-}} \FunctionTok{as.formula}\NormalTok{(}\FunctionTok{paste}\NormalTok{(col, }\StringTok{"\textasciitilde{} Retained.in.2012."}\NormalTok{))}
\NormalTok{  result }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(formula, }\AttributeTok{data =}\NormalTok{ data)}
\NormalTok{  summary\_result }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(result)}
  
  \CommentTok{\# Extract the p{-}value}
\NormalTok{  p\_value }\OtherTok{\textless{}{-}}\NormalTok{ summary\_result[[}\DecValTok{1}\NormalTok{]][}\StringTok{"Pr(\textgreater{}F)"}\NormalTok{][}\DecValTok{1}\NormalTok{]}
  
  \CommentTok{\# Return variable, F{-}statistic, and p{-}value}
  \FunctionTok{list}\NormalTok{(}
    \AttributeTok{Variable =}\NormalTok{ col,}
    \AttributeTok{F\_Value =}\NormalTok{ summary\_result[[}\DecValTok{1}\NormalTok{]][}\StringTok{"F value"}\NormalTok{][}\DecValTok{1}\NormalTok{],}
    \AttributeTok{P\_Value =}\NormalTok{ p\_value}
\NormalTok{  )}
\NormalTok{\})}

\CommentTok{\# Convert results to a data frame}
\NormalTok{anova\_summary }\OtherTok{\textless{}{-}} \FunctionTok{do.call}\NormalTok{(rbind, }\FunctionTok{lapply}\NormalTok{(anova\_results, as.data.frame))}
\NormalTok{anova\_summary }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(anova\_summary)}

\CommentTok{\# View results}
\FunctionTok{print}\NormalTok{(anova\_summary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                                          Variable   F.value        Pr..F.
## Retained.in.2012.                        To.Grade  93.44122  1.038787e-21
## Residuals                                To.Grade        NA            NA
## Retained.in.2012.1                 Is.Non.Annual. 430.96395  3.802842e-88
## Residuals        1                 Is.Non.Annual.        NA            NA
## Retained.in.2012.2                 MDR.High.Grade  42.65254  7.960111e-11
## Residuals        2                 MDR.High.Grade        NA            NA
## Retained.in.2012.3                 School.Sponsor  35.10376  3.577276e-09
## Residuals        3                 School.Sponsor        NA            NA
## Retained.in.2012.4                            FPP 174.31007  1.818712e-38
## Residuals        4                            FPP        NA            NA
## Retained.in.2012.5 DifferenceTraveltoFirstMeeting  36.09014  2.172071e-09
## Residuals        5 DifferenceTraveltoFirstMeeting        NA            NA
## Retained.in.2012.6            SingleGradeTripFlag 628.68106 2.273018e-123
## Residuals        6            SingleGradeTripFlag        NA            NA
## Retained.in.2012.7                     FPP.to.PAX  51.48735  9.572138e-13
## Residuals        7                     FPP.to.PAX        NA            NA
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Save results to a CSV file}
\FunctionTok{write.csv}\NormalTok{(anova\_summary, }\StringTok{"ANOVA\_Test\_Results.csv"}\NormalTok{, }\AttributeTok{row.names =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

All the variables listed are statistically significant because their
p-values (Pr(\textgreater F)) are extremely small (e.g., 1.038787e-21,
3.802842e-88, etc.). SingleGradeTripFlag (F-value: 628.68, p-value:
2.273018e-123) has the highest F-value, suggesting the strongest group
separation.

\#\#Models to Apply

\#Train-Test Split

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Split data into training and testing sets (80{-}20 split)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{train\_index }\OtherTok{\textless{}{-}} \FunctionTok{createDataPartition}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.}\NormalTok{, }\AttributeTok{p =} \FloatTok{0.8}\NormalTok{, }\AttributeTok{list =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{train\_data }\OtherTok{\textless{}{-}}\NormalTok{ data[train\_index, ]}
\NormalTok{test\_data }\OtherTok{\textless{}{-}}\NormalTok{ data[}\SpecialCharTok{{-}}\NormalTok{train\_index, ]}
\end{Highlighting}
\end{Shaded}

\section{Model Training and
Evaluation}\label{model-training-and-evaluation}

\#Decision Tree:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Train Decision Tree}
\NormalTok{dt\_model }\OtherTok{\textless{}{-}} \FunctionTok{rpart}\NormalTok{(Retained.in.}\FloatTok{2012.} \SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ train\_data, }\AttributeTok{method =} \StringTok{"class"}\NormalTok{)}

\CommentTok{\# Predict on test data}
\NormalTok{dt\_predictions }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(dt\_model, test\_data, }\AttributeTok{type =} \StringTok{"class"}\NormalTok{)}

\CommentTok{\# Evaluate using confusion matrix}
\FunctionTok{confusionMatrix}\NormalTok{(dt\_predictions, test\_data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   0   1
##          0 125  31
##          1  62 259
##                                           
##                Accuracy : 0.805           
##                  95% CI : (0.7666, 0.8396)
##     No Information Rate : 0.608           
##     P-Value [Acc > NIR] : < 2.2e-16       
##                                           
##                   Kappa : 0.5786          
##                                           
##  Mcnemar's Test P-Value : 0.001865        
##                                           
##             Sensitivity : 0.6684          
##             Specificity : 0.8931          
##          Pos Pred Value : 0.8013          
##          Neg Pred Value : 0.8069          
##              Prevalence : 0.3920          
##          Detection Rate : 0.2621          
##    Detection Prevalence : 0.3270          
##       Balanced Accuracy : 0.7808          
##                                           
##        'Positive' Class : 0               
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Get predicted probabilities for the positive class (e.g., class \textasciigrave{}1\textasciigrave{})}
\NormalTok{dt\_probabilities }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(dt\_model, test\_data, }\AttributeTok{type =} \StringTok{"prob"}\NormalTok{)[, }\DecValTok{2}\NormalTok{]}

\CommentTok{\# Plot ROC Curve}
\NormalTok{dt\_roc }\OtherTok{\textless{}{-}} \FunctionTok{roc}\NormalTok{(test\_data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.}\NormalTok{, dt\_probabilities)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Setting levels: control = 0, case = 1
\end{verbatim}

\begin{verbatim}
## Setting direction: controls < cases
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(dt\_roc, }\AttributeTok{col =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{main =} \StringTok{"ROC Curve for Decision Tree"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-30-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{auc}\NormalTok{(dt\_roc)  }\CommentTok{\# Print AUC value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Area under the curve: 0.8062
\end{verbatim}

Decision Tree

Strengths: Highest accuracy (0.805) and precision (0.8013), meaning it
performs slightly better overall in correctly classifying both classes.
Highest specificity (0.8931): Best at correctly identifying class 1.
Balanced accuracy (0.7808) indicates good performance on both classes.

Weaknesses: Lowest sensitivity (0.6684): Performs poorly in identifying
class 0. McNemar's test p-value (0.001865) suggests significant bias,
likely favoring class 1. Lowest AUC (0.8062): Indicates relatively
weaker ability to discriminate between classes.

\#random Forest

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Train Random Forest}
\NormalTok{rf\_model }\OtherTok{\textless{}{-}} \FunctionTok{randomForest}\NormalTok{(Retained.in.}\FloatTok{2012.} \SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ train\_data)}

\CommentTok{\# Predict on test data}
\NormalTok{rf\_predictions }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(rf\_model, test\_data)}

\CommentTok{\# Evaluate using confusion matrix}
\FunctionTok{confusionMatrix}\NormalTok{(rf\_predictions, test\_data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   0   1
##          0 127  38
##          1  60 252
##                                           
##                Accuracy : 0.7945          
##                  95% CI : (0.7555, 0.8299)
##     No Information Rate : 0.608           
##     P-Value [Acc > NIR] : < 2e-16         
##                                           
##                   Kappa : 0.5598          
##                                           
##  Mcnemar's Test P-Value : 0.03389         
##                                           
##             Sensitivity : 0.6791          
##             Specificity : 0.8690          
##          Pos Pred Value : 0.7697          
##          Neg Pred Value : 0.8077          
##              Prevalence : 0.3920          
##          Detection Rate : 0.2662          
##    Detection Prevalence : 0.3459          
##       Balanced Accuracy : 0.7741          
##                                           
##        'Positive' Class : 0               
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Get predicted probabilities for the positive class (e.g., class \textasciigrave{}1\textasciigrave{})}
\NormalTok{rf\_probabilities }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(rf\_model, test\_data, }\AttributeTok{type =} \StringTok{"prob"}\NormalTok{)[, }\DecValTok{2}\NormalTok{]}

\CommentTok{\# Plot ROC Curve}
\NormalTok{rf\_roc }\OtherTok{\textless{}{-}} \FunctionTok{roc}\NormalTok{(test\_data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.}\NormalTok{, rf\_probabilities)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Setting levels: control = 0, case = 1
\end{verbatim}

\begin{verbatim}
## Setting direction: controls < cases
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(rf\_roc, }\AttributeTok{col =} \StringTok{"green"}\NormalTok{ , }\AttributeTok{main =} \StringTok{"ROC Curve for randow forest"}\NormalTok{)  }\CommentTok{\# Add to the same plot}
\end{Highlighting}
\end{Shaded}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-31-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{auc}\NormalTok{(rf\_roc)  }\CommentTok{\# Print AUC value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Area under the curve: 0.8692
\end{verbatim}

Random Forest

Strengths: Best AUC (0.87), indicating the strongest ability to
discriminate between classes. High specificity (0.8621): Effective at
correctly identifying class 1. Balanced accuracy (0.7733) is higher than
Logistic Regression but slightly lower than Naive Bayes.

Weaknesses: Moderate sensitivity (0.6845): Similar to Logistic
Regression but misses \textasciitilde31.5\% of actual class 0 cases.
McNemar's test p-value (0.07044) is marginally significant, indicating
slight class imbalance in predictions.

\#Naive Bayes:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Train Naive Bayes}
\NormalTok{nb\_model }\OtherTok{\textless{}{-}} \FunctionTok{naiveBayes}\NormalTok{(Retained.in.}\FloatTok{2012.} \SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ train\_data)}

\CommentTok{\# Predict on test data}
\NormalTok{nb\_predictions }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(nb\_model, test\_data)}

\CommentTok{\# Evaluate using confusion matrix}
\FunctionTok{confusionMatrix}\NormalTok{(nb\_predictions, test\_data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   0   1
##          0 132  44
##          1  55 246
##                                          
##                Accuracy : 0.7925         
##                  95% CI : (0.7532, 0.828)
##     No Information Rate : 0.608          
##     P-Value [Acc > NIR] : <2e-16         
##                                          
##                   Kappa : 0.56           
##                                          
##  Mcnemar's Test P-Value : 0.3149         
##                                          
##             Sensitivity : 0.7059         
##             Specificity : 0.8483         
##          Pos Pred Value : 0.7500         
##          Neg Pred Value : 0.8173         
##              Prevalence : 0.3920         
##          Detection Rate : 0.2767         
##    Detection Prevalence : 0.3690         
##       Balanced Accuracy : 0.7771         
##                                          
##        'Positive' Class : 0              
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Get predicted probabilities for the positive class (e.g., class \textasciigrave{}1\textasciigrave{})}
\NormalTok{nb\_probabilities }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(nb\_model, test\_data, }\AttributeTok{type =} \StringTok{"raw"}\NormalTok{)[, }\DecValTok{2}\NormalTok{]}

\CommentTok{\# Plot ROC Curve}
\NormalTok{nb\_roc }\OtherTok{\textless{}{-}} \FunctionTok{roc}\NormalTok{(test\_data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.}\NormalTok{, nb\_probabilities)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Setting levels: control = 0, case = 1
\end{verbatim}

\begin{verbatim}
## Setting direction: controls < cases
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(nb\_roc, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{, }\AttributeTok{main =} \StringTok{"ROC Curve for Naive Bayes"}\NormalTok{)  }\CommentTok{\# Add to the same plot}
\end{Highlighting}
\end{Shaded}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-32-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{auc}\NormalTok{(nb\_roc)  }\CommentTok{\# Print AUC value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Area under the curve: 0.8507
\end{verbatim}

Naive Bayes Analyse

Strengths: Highest sensitivity (0.7059): Best at identifying class 0
cases. AUC (0.8507) slightly edges out Logistic Regression. Balanced
accuracy (0.7771) is higher than Logistic Regression. McNemar's test
p-value (0.3149): No significant class bias.

Weaknesses: Slightly lower precision (0.7500): More false positives
compared to other models. Specificity (0.8483) is lower than other
models, indicating slightly less accuracy in identifying class 1.

\#Logistic Regression

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Train Logistic Regression}
\NormalTok{lr\_model }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(Retained.in.}\FloatTok{2012.} \SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ train\_data, }\AttributeTok{family =} \StringTok{"binomial"}\NormalTok{)}

\CommentTok{\# Predict probabilities on test data}
\NormalTok{lr\_probabilities }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(lr\_model, test\_data, }\AttributeTok{type =} \StringTok{"response"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
## prediction from rank-deficient fit; attr(*, "non-estim") has doubtful cases
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Convert probabilities to class predictions}
\NormalTok{lr\_predictions }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(lr\_probabilities }\SpecialCharTok{\textgreater{}} \FloatTok{0.5}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}

\CommentTok{\# Evaluate using confusion matrix}
\FunctionTok{confusionMatrix}\NormalTok{(}\FunctionTok{as.factor}\NormalTok{(lr\_predictions), test\_data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   0   1
##          0 127  39
##          1  60 251
##                                          
##                Accuracy : 0.7925         
##                  95% CI : (0.7532, 0.828)
##     No Information Rate : 0.608          
##     P-Value [Acc > NIR] : < 2e-16        
##                                          
##                   Kappa : 0.5557         
##                                          
##  Mcnemar's Test P-Value : 0.04442        
##                                          
##             Sensitivity : 0.6791         
##             Specificity : 0.8655         
##          Pos Pred Value : 0.7651         
##          Neg Pred Value : 0.8071         
##              Prevalence : 0.3920         
##          Detection Rate : 0.2662         
##    Detection Prevalence : 0.3480         
##       Balanced Accuracy : 0.7723         
##                                          
##        'Positive' Class : 0              
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Use predicted probabilities from the logistic regression model}
\NormalTok{lr\_probabilities }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(lr\_model, test\_data, }\AttributeTok{type =} \StringTok{"response"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
## prediction from rank-deficient fit; attr(*, "non-estim") has doubtful cases
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot ROC Curve}
\NormalTok{lr\_roc }\OtherTok{\textless{}{-}} \FunctionTok{roc}\NormalTok{(test\_data}\SpecialCharTok{$}\NormalTok{Retained.in.}\FloatTok{2012.}\NormalTok{, lr\_probabilities)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Setting levels: control = 0, case = 1
\end{verbatim}

\begin{verbatim}
## Setting direction: controls < cases
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(lr\_roc, }\AttributeTok{col =} \StringTok{"purple"}\NormalTok{, }\AttributeTok{main =} \StringTok{"ROC Curve for Logistic Regression"}\NormalTok{)  }\CommentTok{\# Add to the same plot}
\end{Highlighting}
\end{Shaded}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-33-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{auc}\NormalTok{(lr\_roc)  }\CommentTok{\# Print AUC value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Area under the curve: 0.8504
\end{verbatim}

Logistic Regression analyse

\_\_Strengths: AUC of 0.8504 shows strong discrimination capability.
High specificity (0.8655): Effective in correctly identifying class 1.
Balanced accuracy (0.7723) indicates reasonable performance across both
classes. \_\_Weaknesses: Moderate sensitivity (0.6791): Misses
\textasciitilde32\% of actual class 0 cases. McNemar's test p-value
(0.04442) suggests a significant difference in error rates between
classes, indicating potential bias.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot Decision Tree ROC}
\FunctionTok{plot}\NormalTok{(dt\_roc, }\AttributeTok{col =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{main =} \StringTok{"ROC Curves for All Models"}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}

\CommentTok{\# Add other models\textquotesingle{} ROC curves}
\FunctionTok{plot}\NormalTok{(rf\_roc, }\AttributeTok{col =} \StringTok{"green"}\NormalTok{, }\AttributeTok{add =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(nb\_roc, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{, }\AttributeTok{add =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(lr\_roc, }\AttributeTok{col =} \StringTok{"purple"}\NormalTok{, }\AttributeTok{add =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}


\CommentTok{\# Add a legend}
\FunctionTok{legend}\NormalTok{(}\StringTok{"bottomright"}\NormalTok{, }\AttributeTok{legend =} \FunctionTok{c}\NormalTok{(}\StringTok{"Decision Tree"}\NormalTok{, }\StringTok{"Random Forest"}\NormalTok{, }\StringTok{"Naive Bayes"}\NormalTok{, }\StringTok{"Logistic Regression"}\NormalTok{),}
       \AttributeTok{col =} \FunctionTok{c}\NormalTok{(}\StringTok{"blue"}\NormalTok{, }\StringTok{"green"}\NormalTok{, }\StringTok{"red"}\NormalTok{, }\StringTok{"purple"}\NormalTok{), }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{First_Draft_files/figure-latex/unnamed-chunk-34-1.pdf}
ROC Curve Analyst: The ROC curve compares the True Positive Rate
(Sensitivity) against the False Positive Rate (1 - Specificity) for each
model.

Decision Tree (Blue):

This curve is noticeably lower than the others, indicating it is the
least effective model in separating the two classes. The AUC for this
model is the smallest, reflecting relatively weaker performance compared
to the others. Random Forest (Green):

The Random Forest curve is the highest among all models, suggesting it
achieves the best trade-off between sensitivity and specificity. This
model likely has the highest AUC, as it consistently outperforms the
others across all thresholds. Naive Bayes (Red):

The Naive Bayes curve closely follows Random Forest and Logistic
Regression. Its performance is slightly lower than Random Forest but
still competitive, with a strong AUC score. Logistic Regression
(Purple):

Logistic Regression is similar to Naive Bayes and slightly below Random
Forest. The AUC is competitive, though slightly lower than Random
Forest, indicating strong but not the best overall performance.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\begin{quote}
\begin{quote}
Best Model: Random Forest The Random Forest model has the highest AUC
(0.87), strong accuracy (0.7925), and high specificity (0.8621). It
balances sensitivity and specificity better than Logistic Regression and
Decision Tree, making it a reliable choice for this classification task.
\end{quote}
\end{quote}

\begin{quote}
\begin{quote}
Secondary Choice: Naive Bayes Naive Bayes achieves the highest
sensitivity (0.7059) and a competitive AUC (0.8507), making it a good
option if identifying class 0 (minimizing false negatives) is critical.
\end{quote}
\end{quote}

\end{document}
